.TH "include Directory Reference" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctions\&.h\fP"
.br
.ti -1c
.RI "file \fBhuman\&.h\fP"
.br
.ti -1c
.RI "file \fBmanolib\&.h\fP"
.br
.ti -1c
.RI "file \fBstudent\&.h\fP"
.br
.ti -1c
.RI "file \fBvector\&.h\fP"
.br
.in -1c
