.TH "include/functions.h" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/functions.h
.SH SYNOPSIS
.br
.PP
\fR#include 'manolib\&.h'\fP
.br
\fR#include 'student\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTestStud\fP ()"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> \fBContainer\fP \fBGenerateEverything\fP ()"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> \fBContainer\fP \fBGenerateScores\fP ()"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> \fBContainer\fP \fBManualInput\fP ()"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> \fBContainer\fP \fBReadFile\fP (string filename)"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> void \fBSorting\fP (\fBContainer\fP &grupe)"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> void \fBOutputToTerminal\fP (\fBContainer\fP &grupe)"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> void \fBOutputToFile\fP (\fBContainer\fP &grupe)"
.br
.ti -1c
.RI "string \fBGenerateFile\fP (int StudentCount)"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> \fBContainer\fP \fBSpeedTesting\fP ()"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> void \fBSplitFile\fP (\fBContainer\fP &grupe)"
.br
.ti -1c
.RI "template<typename \fBContainer\fP> void \fBFinalScore\fP (\fBContainer\fP &grupe)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename \fBContainer\fP> void FinalScore (\fBContainer\fP & grupe)"

.PP
Definition at line \fB436\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> \fBContainer\fP GenerateEverything ()"

.PP
Definition at line \fB56\fP of file \fBfunctions\&.h\fP\&.
.SS "string GenerateFile (int StudentCount)"

.PP
Definition at line \fB275\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> \fBContainer\fP GenerateScores ()"

.PP
Definition at line \fB100\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> \fBContainer\fP ManualInput ()"

.PP
Definition at line \fB140\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> void OutputToFile (\fBContainer\fP & grupe)"

.PP
Definition at line \fB259\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> void OutputToTerminal (\fBContainer\fP & grupe)"

.PP
Definition at line \fB246\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> \fBContainer\fP ReadFile (string filename)"

.PP
Definition at line \fB170\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> void Sorting (\fBContainer\fP & grupe)"

.PP
Definition at line \fB212\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> \fBContainer\fP SpeedTesting ()"

.PP
Definition at line \fB317\fP of file \fBfunctions\&.h\fP\&.
.SS "template<typename \fBContainer\fP> void SplitFile (\fBContainer\fP & grupe)"

.PP
Definition at line \fB373\fP of file \fBfunctions\&.h\fP\&.
.SS "void TestStud ()"

.PP
Definition at line \fB8\fP of file \fBfunctions\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
