.TH "src/main.cpp" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'manolib\&.h'\fP
.br
\fR#include 'functions\&.h'\fP
.br
\fR#include 'student\&.h'\fP
.br
\fR#include 'vector\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBContainer\fP = \fBVektor\fP<\fBStud\fP>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBContainer\fP = \fBVektor\fP<\fBStud\fP>"

.PP
Definition at line \fB7\fP of file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB11\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
