.TH "include/manolib.h" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/manolib.h
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <list>\fP
.br
\fR#include <deque>\fP
.br
\fR#include <iomanip>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <ctime>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <string>\fP
.br
\fR#include <type_traits>\fP
.br
\fR#include <exception>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBMNames\fP [25]"
.br
.ti -1c
.RI "const string \fBMSurnames\fP [25]"
.br
.ti -1c
.RI "const string \fBFNames\fP [25]"
.br
.ti -1c
.RI "const string \fBFSurnames\fP [25]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string FNames[25]"
\fBInitial value:\fP
.nf
= {
    "Egle", "Indre", "Lina","Neringa","Sigute","Ugne","Laura","Viktorija",
    "Rasa","Gintare","Agne","Ieva", "Milda","Margarita","Aiste", "Vilma",
    "Ruta","Aiste","Gabija","Jurate","Jurgita", "Vaiva", "Ula", "Greta",
    "Kotryna"

}
.PP
.fi

.PP
Definition at line \fB57\fP of file \fBmanolib\&.h\fP\&.
.SS "const string FSurnames[25]"
\fBInitial value:\fP
.nf
= {
"Norkute","Petronyte","Seskinyte","Pakalnaite","Daugelaite","Simonaityte",
"Giedre","Zukaite", "Norkute", "Kaminskaite", "Dapsyte", "Kucinskaite", 
"Vaitkeviciute", "Vasiliauskaite", "Navickaite", "Urbonaite", "Grigoniene",
 "Rutkauskaite", "Vaitkute", "Pakalnyte", "Norkute", "Skripkaite", "Butkeviciute",
"Mickeviciute", "Brazaite"
}
.PP
.fi

.PP
Definition at line \fB64\fP of file \fBmanolib\&.h\fP\&.
.SS "const string MNames[25]"
\fBInitial value:\fP
.nf
= {
    "Andrius", "Dainius", "Jonas" , "Marius", "Orestas", "Povilas", 
    "Aidas",  "Tomas",  "Vejas", "Zygimantas",  "Vaidotas",
    "Linas", "Kestutis", "Vaidotas", "Martynas",   "Gintaras",
     "Tomas", "Antanas", "Paulius",   "Jonas",  "Mantas", 
     "Mindaugas", "Rokas", "Lukas", "Kazimieras"
}
.PP
.fi

.PP
Definition at line \fB44\fP of file \fBmanolib\&.h\fP\&.
.SS "const string MSurnames[25]"
\fBInitial value:\fP
.nf
= {
    "Petrauskas", "Jankauskas", "Kazlauskas", "Zukauskas", "Kavaliauskas", "Stankevicius", "Bieliauskas", 
    "Budvytis", "Giedraitis",  "Rimkus",  "Valiukas", "Juknevicius", "Vaitkevicius", 
     "Vasiliauskas", "Navickas",  "Urbonas", "Grigonis", "Rutkauskas",  
    "Vaitkus", "Pakalnis", "Norkus", "Skripka", "Butkevicius", "Nedzinskas", "Mickevicius",  
}
.PP
.fi

.PP
Definition at line \fB51\fP of file \fBmanolib\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
