.TH "include/student.h" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/student.h
.SH SYNOPSIS
.br
.PP
\fR#include 'human\&.h'\fP
.br
\fR#include 'manolib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStud\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
