.TH "src/tests.cpp" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'catch\&.hpp'\fP
.br
\fR#include 'student\&.h'\fP
.br
\fR#include 'human\&.h'\fP
.br
\fR#include 'manolib\&.h'\fP
.br
\fR#include 'functions\&.h'\fP
.br
\fR#include 'vector\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCATCH_CONFIG_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_CASE\fP ('Studentu klases penkiu pirstu taisykles testas')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Kitu programos funkciju testai')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('Vektoriaus klasės testai')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CATCH_CONFIG_MAIN"

.PP
Definition at line \fB1\fP of file \fBtests\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST_CASE ('Kitu programos funkciju testai' )"

.PP
Definition at line \fB69\fP of file \fBtests\&.cpp\fP\&.
.SS "TEST_CASE ('Studentu klases penkiu pirstu taisykles testas' )"

.PP
Definition at line \fB10\fP of file \fBtests\&.cpp\fP\&.
.SS "TEST_CASE ('Vektoriaus klasės testai' )"

.PP
Definition at line \fB83\fP of file \fBtests\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
