.TH "Zmogus" 3 "Studentų galutinio balo skaičiuoklė" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zmogus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <human\&.h>\fP
.PP
Inherited by \fBStud\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZmogus\fP ()"
.br
.ti -1c
.RI "\fBZmogus\fP (const string &v, const string &p)"
.br
.ti -1c
.RI "virtual \fB~Zmogus\fP ()=default"
.br
.ti -1c
.RI "string \fBgetVardas\fP () const"
.br
.ti -1c
.RI "string \fBgetPavarde\fP () const"
.br
.ti -1c
.RI "void \fBsetVardas\fP (const string &v)"
.br
.ti -1c
.RI "void \fBsetPavarde\fP (const string &p)"
.br
.ti -1c
.RI "virtual void \fBprint\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBVardas\fP"
.br
.ti -1c
.RI "string \fBPavarde\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBhuman\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zmogus::Zmogus ()\fR [inline]\fP"

.PP
Definition at line \fB9\fP of file \fBhuman\&.h\fP\&.
.SS "Zmogus::Zmogus (const string & v, const string & p)\fR [inline]\fP"

.PP
Definition at line \fB10\fP of file \fBhuman\&.h\fP\&.
.SS "virtual Zmogus::~Zmogus ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "string Zmogus::getPavarde () const\fR [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBhuman\&.h\fP\&.
.SS "string Zmogus::getVardas () const\fR [inline]\fP"

.PP
Definition at line \fB14\fP of file \fBhuman\&.h\fP\&.
.SS "virtual void Zmogus::print () const\fR [pure virtual]\fP"

.PP
Implemented in \fBStud\fP\&.
.SS "void Zmogus::setPavarde (const string & p)\fR [inline]\fP"

.PP
Definition at line \fB18\fP of file \fBhuman\&.h\fP\&.
.SS "void Zmogus::setVardas (const string & v)\fR [inline]\fP"

.PP
Definition at line \fB17\fP of file \fBhuman\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Zmogus::Pavarde\fR [protected]\fP"

.PP
Definition at line \fB6\fP of file \fBhuman\&.h\fP\&.
.SS "string Zmogus::Vardas\fR [protected]\fP"

.PP
Definition at line \fB6\fP of file \fBhuman\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Studentų galutinio balo skaičiuoklė from the source code\&.
